### ISSUE TITLE
Clickboard Doesnt Work in TDM and CTF

### ISSUE THREAD

**Issue by Deaod** [Deaod/InstaGibPlus#7]

**Comment by deltabatonix** [comment]
Here few screenshots with different server settings (bTournament= False and True)

In Warmup (bTournament=True) - green ready flag not displayed:
![InWarmup-noflag-tournament-true](https://user-images.githubusercontent.com/74108718/110507637-17888600-80f8-11eb-9fa4-8bffaab2f73a.png)

Waiting for the game to start (bTournament=False) - green ready flag displayed
![Shot00003](https://user-images.githubusercontent.com/74108718/110507847-53235000-80f8-11eb-9746-49c2d11d8c9e.png)

Game has started - green ready flag still displayed
![Shot00004](https://user-images.githubusercontent.com/74108718/110507931-67674d00-80f8-11eb-8c77-ca0d27548bd0.png)

This is hit or miss, I cant really find pattern or cause for not being able to reproduce it more reliably.

**Comment by deltabatonix** [comment]
Fixed in the newest build!

**Comment by Deaod** [comment]
Fixed in 77f4c92163604dd67039da11a3dc06fb521fc9d6
